# Generated by Django 4.2.7 on 2025-09-09 08:26

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=apps.users.models.User.generate_user_id,
                help_text="Human-friendly unique identifier (auto-generated if omitted)",
                max_length=32,
                unique=True,
            ),
        ),
    ]
