# Generated by Django 4.2.7 on 2025-09-08 21:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization_id",
                    models.CharField(
                        help_text="Unique identifier for the organization within the account",
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Organization ID can only contain letters, numbers, underscores, and hyphens.",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                ("organization_name", models.CharField(max_length=255)),
                (
                    "organization_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "organization_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("organization_website", models.URLField(blank=True, null=True)),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("timezone", models.CharField(blank=True, max_length=50, null=True)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                ("max_users", models.PositiveIntegerField(default=10)),
                ("max_teams", models.PositiveIntegerField(default=5)),
                ("max_storage_gb", models.PositiveIntegerField(default=1)),
                ("features", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organizations",
                "ordering": ["organization_name"],
            },
        ),
    ]
